export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL='REGISTER_FAIL';
export const REGISTER_ATTEMPT='REGISTER_ATTEMPT';

export const USER_LOADED='USER_LOADED';
export const AUTH_ERROR= 'AUTH_ERROR';

export const LOGIN_SUCCESS= 'LOGIN_SUCCESS';
export const LOGIN_FAIL= 'LOGIN_FAIL';
export const LOGIN_ATTEMPT= 'LOGIN_ATTEMPT';

export const FETCH_FAIL= 'FETCH_FAIL';
export const FETCH_SUCCESS= 'FETCH_SUCCESS';
export const FETCH_ATTEMPT= 'FETCH_ATTEMPT';

export const FETCH_ACCEPTED= 'FETCH_ACCEPTED';
export const FETCH_ACCEPTED_SUCCESS= 'FETCH_ACCEPTED_SUCCESS';
export const FETCH_ACCEPTED_FAIL= 'FETCH_ACCEPTED_FAIL';


export const FETCH_PREVIOUS= 'FETCH_PREVIOUS';
export const FETCH_PREVIOUS_SUCCESS= 'FETCH_PREVIOUS_SUCCESS';
export const FETCH_PREVIOUS_FAIL= 'FETCH_PREVIOUS_FAIL';
export const ATTEMPT= 'ATTEMPT';


export const FETCH_REVIEWS = "FETCH_REVIEWS";
export const FETCH_REVIEW_FAIL = "FETCH_REVIEW_FAIL"

export const LOGOUT = "LOGOUT"